// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: briefings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getBriefingBySession = `-- name: GetBriefingBySession :one
SELECT id, session_id, summary_text, top_keywords, emotion_flag, model, generated_at, read_by_caregiver_at FROM briefing_report WHERE session_id = $1
`

func (q *Queries) GetBriefingBySession(ctx context.Context, sessionID uuid.UUID) (BriefingReport, error) {
	row := q.db.QueryRow(ctx, getBriefingBySession, sessionID)
	var i BriefingReport
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryText,
		&i.TopKeywords,
		&i.EmotionFlag,
		&i.Model,
		&i.GeneratedAt,
		&i.ReadByCaregiverAt,
	)
	return i, err
}

const markBriefingRead = `-- name: MarkBriefingRead :one
UPDATE briefing_report
SET read_by_caregiver_at = COALESCE(read_by_caregiver_at, now())
WHERE session_id = $1
RETURNING id, session_id, summary_text, top_keywords, emotion_flag, model, generated_at, read_by_caregiver_at
`

func (q *Queries) MarkBriefingRead(ctx context.Context, sessionID uuid.UUID) (BriefingReport, error) {
	row := q.db.QueryRow(ctx, markBriefingRead, sessionID)
	var i BriefingReport
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryText,
		&i.TopKeywords,
		&i.EmotionFlag,
		&i.Model,
		&i.GeneratedAt,
		&i.ReadByCaregiverAt,
	)
	return i, err
}
