// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: caregivers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCaregiver = `-- name: GetCaregiver :one
SELECT id, name, center_id, created_at, login_id, password_hash FROM caregiver WHERE id = $1
`

func (q *Queries) GetCaregiver(ctx context.Context, id uuid.UUID) (Caregiver, error) {
	row := q.db.QueryRow(ctx, getCaregiver, id)
	var i Caregiver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CenterID,
		&i.CreatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}

const getCaregiverByLoginID = `-- name: GetCaregiverByLoginID :one
SELECT id, name, center_id, created_at, login_id, password_hash FROM caregiver WHERE login_id = $1
`

func (q *Queries) GetCaregiverByLoginID(ctx context.Context, loginID *string) (Caregiver, error) {
	row := q.db.QueryRow(ctx, getCaregiverByLoginID, loginID)
	var i Caregiver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CenterID,
		&i.CreatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}

const setCaregiverLogin = `-- name: SetCaregiverLogin :one
UPDATE caregiver
SET login_id = $1,
    password_hash = $2
WHERE id = $3
RETURNING id, name, center_id, created_at, login_id, password_hash
`

type SetCaregiverLoginParams struct {
	LoginID      *string   `json:"login_id"`
	PasswordHash *string   `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) SetCaregiverLogin(ctx context.Context, arg SetCaregiverLoginParams) (Caregiver, error) {
	row := q.db.QueryRow(ctx, setCaregiverLogin, arg.LoginID, arg.PasswordHash, arg.ID)
	var i Caregiver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CenterID,
		&i.CreatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}
