// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createElderTablet = `-- name: CreateElderTablet :one
INSERT INTO device (kind, elder_id, token_hash, label)
VALUES ('ELDER_TABLET', $1, $2, $3)
RETURNING id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at
`

type CreateElderTabletParams struct {
	ElderID   *uuid.UUID `json:"elder_id"`
	TokenHash []byte     `json:"token_hash"`
	Label     *string    `json:"label"`
}

func (q *Queries) CreateElderTablet(ctx context.Context, arg CreateElderTabletParams) (Device, error) {
	row := q.db.QueryRow(ctx, createElderTablet, arg.ElderID, arg.TokenHash, arg.Label)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ElderID,
		&i.CaregiverID,
		&i.GuardianID,
		&i.Label,
		&i.TokenHash,
		&i.FcmToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveDeviceByTokenHash = `-- name: GetActiveDeviceByTokenHash :one
SELECT id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at FROM device WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveDeviceByTokenHash(ctx context.Context, tokenHash []byte) (Device, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ElderID,
		&i.CaregiverID,
		&i.GuardianID,
		&i.Label,
		&i.TokenHash,
		&i.FcmToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCaregiverPhones = `-- name: ListCaregiverPhones :many
SELECT id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at FROM device
WHERE kind = 'CAREGIVER_PHONE'
  AND caregiver_id = $1
  AND revoked_at IS NULL
  AND fcm_token IS NOT NULL
`

// 위급 알림을 보낼 조무사 휴대폰들.
func (q *Queries) ListCaregiverPhones(ctx context.Context, caregiverID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listCaregiverPhones, caregiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ElderID,
			&i.CaregiverID,
			&i.GuardianID,
			&i.Label,
			&i.TokenHash,
			&i.FcmToken,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerCaregiverPhone = `-- name: RegisterCaregiverPhone :one
INSERT INTO device (kind, caregiver_id, fcm_token, label)
VALUES ('CAREGIVER_PHONE', $1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE
SET kind = 'CAREGIVER_PHONE',
    caregiver_id = EXCLUDED.caregiver_id,
    guardian_id = NULL,
    elder_id = NULL,
    label = EXCLUDED.label,
    revoked_at = NULL
RETURNING id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at
`

type RegisterCaregiverPhoneParams struct {
	CaregiverID *uuid.UUID `json:"caregiver_id"`
	FcmToken    *string    `json:"fcm_token"`
	Label       *string    `json:"label"`
}

// 같은 FCM 토큰이 다시 오면 주인을 바꾸고 되살립니다(앱 재설치·로그인 전환).
func (q *Queries) RegisterCaregiverPhone(ctx context.Context, arg RegisterCaregiverPhoneParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerCaregiverPhone, arg.CaregiverID, arg.FcmToken, arg.Label)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ElderID,
		&i.CaregiverID,
		&i.GuardianID,
		&i.Label,
		&i.TokenHash,
		&i.FcmToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeDeviceByFcmToken = `-- name: RevokeDeviceByFcmToken :exec
UPDATE device SET revoked_at = now() WHERE fcm_token = $1 AND revoked_at IS NULL
`

// FCM이 등록되지 않은 토큰이라고 답하면 다시 보내지 않습니다.
func (q *Queries) RevokeDeviceByFcmToken(ctx context.Context, fcmToken *string) error {
	_, err := q.db.Exec(ctx, revokeDeviceByFcmToken, fcmToken)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE device SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}
