// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanionSchedule = `-- name: GetCompanionSchedule :one
SELECT elder_id, enabled, check_in_times, bedtime_start, bedtime_end, time_zone, daily_token_limit, created_at, updated_at FROM companion_schedule WHERE elder_id = $1
`

func (q *Queries) GetCompanionSchedule(ctx context.Context, elderID uuid.UUID) (CompanionSchedule, error) {
	row := q.db.QueryRow(ctx, getCompanionSchedule, elderID)
	var i CompanionSchedule
	err := row.Scan(
		&i.ElderID,
		&i.Enabled,
		&i.CheckInTimes,
		&i.BedtimeStart,
		&i.BedtimeEnd,
		&i.TimeZone,
		&i.DailyTokenLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyDigest = `-- name: GetDailyDigest :one
SELECT id, elder_id, digest_date, summary_text, emotion_flag, session_count, escalation_count, total_tokens, model, generated_at, sent_at FROM daily_digest WHERE elder_id = $1 AND digest_date = $2
`

type GetDailyDigestParams struct {
	ElderID    uuid.UUID   `json:"elder_id"`
	DigestDate pgtype.Date `json:"digest_date"`
}

func (q *Queries) GetDailyDigest(ctx context.Context, arg GetDailyDigestParams) (DailyDigest, error) {
	row := q.db.QueryRow(ctx, getDailyDigest, arg.ElderID, arg.DigestDate)
	var i DailyDigest
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.DigestDate,
		&i.SummaryText,
		&i.EmotionFlag,
		&i.SessionCount,
		&i.EscalationCount,
		&i.TotalTokens,
		&i.Model,
		&i.GeneratedAt,
		&i.SentAt,
	)
	return i, err
}

const getElder = `-- name: GetElder :one
SELECT id, name, birth_date, dementia_stage, preferred_tts_voice, guardian_id, center_id, created_at, updated_at, home_address, home_latitude, home_longitude FROM elder WHERE id = $1
`

func (q *Queries) GetElder(ctx context.Context, id uuid.UUID) (Elder, error) {
	row := q.db.QueryRow(ctx, getElder, id)
	var i Elder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.DementiaStage,
		&i.PreferredTtsVoice,
		&i.GuardianID,
		&i.CenterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeAddress,
		&i.HomeLatitude,
		&i.HomeLongitude,
	)
	return i, err
}

const upsertCompanionSchedule = `-- name: UpsertCompanionSchedule :one
INSERT INTO companion_schedule (elder_id, enabled, check_in_times, bedtime_start, bedtime_end, time_zone, daily_token_limit)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (elder_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    check_in_times = EXCLUDED.check_in_times,
    bedtime_start = EXCLUDED.bedtime_start,
    bedtime_end = EXCLUDED.bedtime_end,
    time_zone = EXCLUDED.time_zone,
    daily_token_limit = EXCLUDED.daily_token_limit
RETURNING elder_id, enabled, check_in_times, bedtime_start, bedtime_end, time_zone, daily_token_limit, created_at, updated_at
`

type UpsertCompanionScheduleParams struct {
	ElderID         uuid.UUID     `json:"elder_id"`
	Enabled         bool          `json:"enabled"`
	CheckInTimes    []pgtype.Time `json:"check_in_times"`
	BedtimeStart    pgtype.Time   `json:"bedtime_start"`
	BedtimeEnd      pgtype.Time   `json:"bedtime_end"`
	TimeZone        string        `json:"time_zone"`
	DailyTokenLimit *int32        `json:"daily_token_limit"`
}

func (q *Queries) UpsertCompanionSchedule(ctx context.Context, arg UpsertCompanionScheduleParams) (CompanionSchedule, error) {
	row := q.db.QueryRow(ctx, upsertCompanionSchedule,
		arg.ElderID,
		arg.Enabled,
		arg.CheckInTimes,
		arg.BedtimeStart,
		arg.BedtimeEnd,
		arg.TimeZone,
		arg.DailyTokenLimit,
	)
	var i CompanionSchedule
	err := row.Scan(
		&i.ElderID,
		&i.Enabled,
		&i.CheckInTimes,
		&i.BedtimeStart,
		&i.BedtimeEnd,
		&i.TimeZone,
		&i.DailyTokenLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
