// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: escalations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const acknowledgeEscalation = `-- name: AcknowledgeEscalation :one
UPDATE escalation_event
SET acknowledged_at = COALESCE(acknowledged_at, now()),
    acknowledged_by_caregiver_id = COALESCE(acknowledged_by_caregiver_id, $1)
WHERE id = $2
RETURNING id, session_id, utterance_id, trigger_type, source, rule_id, reason, notified_targets, created_at, acknowledged_at, acknowledged_by_caregiver_id, resolved_at
`

type AcknowledgeEscalationParams struct {
	CaregiverID *uuid.UUID `json:"caregiver_id"`
	ID          uuid.UUID  `json:"id"`
}

// 여러 번 눌러도 처음 확인한 시각과 사람이 남습니다.
func (q *Queries) AcknowledgeEscalation(ctx context.Context, arg AcknowledgeEscalationParams) (EscalationEvent, error) {
	row := q.db.QueryRow(ctx, acknowledgeEscalation, arg.CaregiverID, arg.ID)
	var i EscalationEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UtteranceID,
		&i.TriggerType,
		&i.Source,
		&i.RuleID,
		&i.Reason,
		&i.NotifiedTargets,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByCaregiverID,
		&i.ResolvedAt,
	)
	return i, err
}

const createEscalationEvent = `-- name: CreateEscalationEvent :one
INSERT INTO escalation_event (session_id, utterance_id, trigger_type, source, rule_id, reason, notified_targets)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, session_id, utterance_id, trigger_type, source, rule_id, reason, notified_targets, created_at, acknowledged_at, acknowledged_by_caregiver_id, resolved_at
`

type CreateEscalationEventParams struct {
	SessionID       uuid.UUID  `json:"session_id"`
	UtteranceID     *uuid.UUID `json:"utterance_id"`
	TriggerType     string     `json:"trigger_type"`
	Source          string     `json:"source"`
	RuleID          *string    `json:"rule_id"`
	Reason          *string    `json:"reason"`
	NotifiedTargets []byte     `json:"notified_targets"`
}

func (q *Queries) CreateEscalationEvent(ctx context.Context, arg CreateEscalationEventParams) (EscalationEvent, error) {
	row := q.db.QueryRow(ctx, createEscalationEvent,
		arg.SessionID,
		arg.UtteranceID,
		arg.TriggerType,
		arg.Source,
		arg.RuleID,
		arg.Reason,
		arg.NotifiedTargets,
	)
	var i EscalationEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UtteranceID,
		&i.TriggerType,
		&i.Source,
		&i.RuleID,
		&i.Reason,
		&i.NotifiedTargets,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByCaregiverID,
		&i.ResolvedAt,
	)
	return i, err
}

const getEscalationEvent = `-- name: GetEscalationEvent :one
SELECT id, session_id, utterance_id, trigger_type, source, rule_id, reason, notified_targets, created_at, acknowledged_at, acknowledged_by_caregiver_id, resolved_at FROM escalation_event WHERE id = $1
`

func (q *Queries) GetEscalationEvent(ctx context.Context, id uuid.UUID) (EscalationEvent, error) {
	row := q.db.QueryRow(ctx, getEscalationEvent, id)
	var i EscalationEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UtteranceID,
		&i.TriggerType,
		&i.Source,
		&i.RuleID,
		&i.Reason,
		&i.NotifiedTargets,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByCaregiverID,
		&i.ResolvedAt,
	)
	return i, err
}
