// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guardians.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acknowledgeEscalationByGuardian = `-- name: AcknowledgeEscalationByGuardian :one
UPDATE escalation_event
SET acknowledged_at = COALESCE(acknowledged_at, now()),
    acknowledged_by_guardian_id = COALESCE(acknowledged_by_guardian_id, $1)
WHERE id = $2
RETURNING id, session_id, utterance_id, trigger_type, source, rule_id, reason, notified_targets, created_at, acknowledged_at, acknowledged_by_caregiver_id, resolved_at, acknowledged_by_guardian_id
`

type AcknowledgeEscalationByGuardianParams struct {
	GuardianID *uuid.UUID `json:"guardian_id"`
	ID         uuid.UUID  `json:"id"`
}

// 여러 번 눌러도 처음 확인한 시각과 사람이 남습니다.
func (q *Queries) AcknowledgeEscalationByGuardian(ctx context.Context, arg AcknowledgeEscalationByGuardianParams) (EscalationEvent, error) {
	row := q.db.QueryRow(ctx, acknowledgeEscalationByGuardian, arg.GuardianID, arg.ID)
	var i EscalationEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UtteranceID,
		&i.TriggerType,
		&i.Source,
		&i.RuleID,
		&i.Reason,
		&i.NotifiedTargets,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByCaregiverID,
		&i.ResolvedAt,
		&i.AcknowledgedByGuardianID,
	)
	return i, err
}

const getGuardian = `-- name: GetGuardian :one
SELECT id, name, phone, notification_preference, created_at, updated_at, login_id, password_hash FROM guardian WHERE id = $1
`

func (q *Queries) GetGuardian(ctx context.Context, id uuid.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardian, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.NotificationPreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}

const getGuardianByLoginID = `-- name: GetGuardianByLoginID :one
SELECT id, name, phone, notification_preference, created_at, updated_at, login_id, password_hash FROM guardian WHERE login_id = $1
`

func (q *Queries) GetGuardianByLoginID(ctx context.Context, loginID *string) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByLoginID, loginID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.NotificationPreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}

const getGuardianEscalation = `-- name: GetGuardianEscalation :one
SELECT
    escalation_event.id, escalation_event.session_id, escalation_event.utterance_id, escalation_event.trigger_type, escalation_event.source, escalation_event.rule_id, escalation_event.reason, escalation_event.notified_targets, escalation_event.created_at, escalation_event.acknowledged_at, escalation_event.acknowledged_by_caregiver_id, escalation_event.resolved_at, escalation_event.acknowledged_by_guardian_id,
    elder.id AS elder_id,
    elder.name AS elder_name,
    utterance.text AS utterance_text,
    conversation_session.mode AS session_mode
FROM escalation_event
JOIN conversation_session ON conversation_session.id = escalation_event.session_id
JOIN elder ON elder.id = conversation_session.elder_id
LEFT JOIN utterance ON utterance.id = escalation_event.utterance_id
WHERE escalation_event.id = $1
  AND elder.guardian_id = $2
`

type GetGuardianEscalationParams struct {
	ID         uuid.UUID `json:"id"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

type GetGuardianEscalationRow struct {
	EscalationEvent EscalationEvent `json:"escalation_event"`
	ElderID         uuid.UUID       `json:"elder_id"`
	ElderName       string          `json:"elder_name"`
	UtteranceText   *string         `json:"utterance_text"`
	SessionMode     string          `json:"session_mode"`
}

// 보호자가 받은 알림을 열 때. 다른 집 어르신의 위급이면 행이 없습니다.
func (q *Queries) GetGuardianEscalation(ctx context.Context, arg GetGuardianEscalationParams) (GetGuardianEscalationRow, error) {
	row := q.db.QueryRow(ctx, getGuardianEscalation, arg.ID, arg.GuardianID)
	var i GetGuardianEscalationRow
	err := row.Scan(
		&i.EscalationEvent.ID,
		&i.EscalationEvent.SessionID,
		&i.EscalationEvent.UtteranceID,
		&i.EscalationEvent.TriggerType,
		&i.EscalationEvent.Source,
		&i.EscalationEvent.RuleID,
		&i.EscalationEvent.Reason,
		&i.EscalationEvent.NotifiedTargets,
		&i.EscalationEvent.CreatedAt,
		&i.EscalationEvent.AcknowledgedAt,
		&i.EscalationEvent.AcknowledgedByCaregiverID,
		&i.EscalationEvent.ResolvedAt,
		&i.EscalationEvent.AcknowledgedByGuardianID,
		&i.ElderID,
		&i.ElderName,
		&i.UtteranceText,
		&i.SessionMode,
	)
	return i, err
}

const listGuardianElders = `-- name: ListGuardianElders :many
SELECT id, name FROM elder WHERE guardian_id = $1 ORDER BY name
`

type ListGuardianEldersRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// 보호자가 돌보는 어르신. 보호자 앱의 모든 조회는 이 목록 안으로 제한합니다.
func (q *Queries) ListGuardianElders(ctx context.Context, guardianID uuid.UUID) ([]ListGuardianEldersRow, error) {
	rows, err := q.db.Query(ctx, listGuardianElders, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuardianEldersRow{}
	for rows.Next() {
		var i ListGuardianEldersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardianPhones = `-- name: ListGuardianPhones :many
SELECT id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at FROM device
WHERE kind = 'GUARDIAN_PHONE'
  AND guardian_id = $1
  AND revoked_at IS NULL
  AND fcm_token IS NOT NULL
`

func (q *Queries) ListGuardianPhones(ctx context.Context, guardianID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listGuardianPhones, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ElderID,
			&i.CaregiverID,
			&i.GuardianID,
			&i.Label,
			&i.TokenHash,
			&i.FcmToken,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenEscalationsForGuardian = `-- name: ListOpenEscalationsForGuardian :many
SELECT
    escalation_event.id, escalation_event.session_id, escalation_event.utterance_id, escalation_event.trigger_type, escalation_event.source, escalation_event.rule_id, escalation_event.reason, escalation_event.notified_targets, escalation_event.created_at, escalation_event.acknowledged_at, escalation_event.acknowledged_by_caregiver_id, escalation_event.resolved_at, escalation_event.acknowledged_by_guardian_id,
    elder.id AS elder_id,
    elder.name AS elder_name,
    utterance.text AS utterance_text
FROM escalation_event
JOIN conversation_session ON conversation_session.id = escalation_event.session_id
JOIN elder ON elder.id = conversation_session.elder_id
LEFT JOIN utterance ON utterance.id = escalation_event.utterance_id
WHERE elder.guardian_id = $1
  AND conversation_session.mode = 'COMPANION'
  AND escalation_event.acknowledged_at IS NULL
  AND escalation_event.created_at >= $2
ORDER BY escalation_event.created_at DESC
`

type ListOpenEscalationsForGuardianParams struct {
	GuardianID uuid.UUID `json:"guardian_id"`
	Since      time.Time `json:"since"`
}

type ListOpenEscalationsForGuardianRow struct {
	EscalationEvent EscalationEvent `json:"escalation_event"`
	ElderID         uuid.UUID       `json:"elder_id"`
	ElderName       string          `json:"elder_name"`
	UtteranceText   *string         `json:"utterance_text"`
}

// 보호자가 확인하지 않은 위급. 말동무 세션(방문 없는 대화)만 보호자에게 보입니다.
func (q *Queries) ListOpenEscalationsForGuardian(ctx context.Context, arg ListOpenEscalationsForGuardianParams) ([]ListOpenEscalationsForGuardianRow, error) {
	rows, err := q.db.Query(ctx, listOpenEscalationsForGuardian, arg.GuardianID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenEscalationsForGuardianRow{}
	for rows.Next() {
		var i ListOpenEscalationsForGuardianRow
		if err := rows.Scan(
			&i.EscalationEvent.ID,
			&i.EscalationEvent.SessionID,
			&i.EscalationEvent.UtteranceID,
			&i.EscalationEvent.TriggerType,
			&i.EscalationEvent.Source,
			&i.EscalationEvent.RuleID,
			&i.EscalationEvent.Reason,
			&i.EscalationEvent.NotifiedTargets,
			&i.EscalationEvent.CreatedAt,
			&i.EscalationEvent.AcknowledgedAt,
			&i.EscalationEvent.AcknowledgedByCaregiverID,
			&i.EscalationEvent.ResolvedAt,
			&i.EscalationEvent.AcknowledgedByGuardianID,
			&i.ElderID,
			&i.ElderName,
			&i.UtteranceText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDigests = `-- name: ListRecentDigests :many
SELECT id, elder_id, digest_date, summary_text, emotion_flag, session_count, escalation_count, total_tokens, model, generated_at, sent_at FROM daily_digest
WHERE elder_id = $1
ORDER BY digest_date DESC
LIMIT $2
`

type ListRecentDigestsParams struct {
	ElderID  uuid.UUID `json:"elder_id"`
	MaxCount int32     `json:"max_count"`
}

// 보호자 앱 홈: 어르신의 최근 하루 요약.
func (q *Queries) ListRecentDigests(ctx context.Context, arg ListRecentDigestsParams) ([]DailyDigest, error) {
	rows, err := q.db.Query(ctx, listRecentDigests, arg.ElderID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyDigest{}
	for rows.Next() {
		var i DailyDigest
		if err := rows.Scan(
			&i.ID,
			&i.ElderID,
			&i.DigestDate,
			&i.SummaryText,
			&i.EmotionFlag,
			&i.SessionCount,
			&i.EscalationCount,
			&i.TotalTokens,
			&i.Model,
			&i.GeneratedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerGuardianPhone = `-- name: RegisterGuardianPhone :one
INSERT INTO device (kind, guardian_id, fcm_token, label, last_seen_at)
VALUES ('GUARDIAN_PHONE', $1, $2, $3, now())
ON CONFLICT (fcm_token) DO UPDATE
SET kind = 'GUARDIAN_PHONE',
    guardian_id = EXCLUDED.guardian_id,
    caregiver_id = NULL,
    elder_id = NULL,
    label = EXCLUDED.label,
    revoked_at = NULL,
    last_seen_at = now()
RETURNING id, kind, elder_id, caregiver_id, guardian_id, label, token_hash, fcm_token, last_seen_at, revoked_at, created_at
`

type RegisterGuardianPhoneParams struct {
	GuardianID *uuid.UUID `json:"guardian_id"`
	FcmToken   *string    `json:"fcm_token"`
	Label      *string    `json:"label"`
}

// 같은 FCM 토큰이 다시 오면 보호자와 이름만 갱신합니다(기기 초기화·재설치).
func (q *Queries) RegisterGuardianPhone(ctx context.Context, arg RegisterGuardianPhoneParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerGuardianPhone, arg.GuardianID, arg.FcmToken, arg.Label)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ElderID,
		&i.CaregiverID,
		&i.GuardianID,
		&i.Label,
		&i.TokenHash,
		&i.FcmToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setGuardianLogin = `-- name: SetGuardianLogin :one
UPDATE guardian
SET login_id = $1,
    password_hash = $2
WHERE id = $3
RETURNING id, name, phone, notification_preference, created_at, updated_at, login_id, password_hash
`

type SetGuardianLoginParams struct {
	LoginID      *string   `json:"login_id"`
	PasswordHash *string   `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) SetGuardianLogin(ctx context.Context, arg SetGuardianLoginParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, setGuardianLogin, arg.LoginID, arg.PasswordHash, arg.ID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.NotificationPreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginID,
		&i.PasswordHash,
	)
	return i, err
}
