// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keywords.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpKeyword = `-- name: BumpKeyword :one
INSERT INTO keyword_tag (elder_id, keyword, category, score, emotion_tone, last_mentioned_at, mention_count_total)
VALUES (
    $1, $2, $3, $4::integer,
    $5, $6, $4::integer
)
ON CONFLICT (elder_id, keyword) DO UPDATE
SET score = keyword_tag.score * 0.9 + EXCLUDED.score,
    category = EXCLUDED.category,
    emotion_tone = EXCLUDED.emotion_tone,
    last_mentioned_at = EXCLUDED.last_mentioned_at,
    mention_count_total = keyword_tag.mention_count_total + EXCLUDED.mention_count_total
RETURNING id, elder_id, keyword, category, score, emotion_tone, last_mentioned_at, mention_count_total, created_at, updated_at
`

type BumpKeywordParams struct {
	ElderID     uuid.UUID `json:"elder_id"`
	Keyword     string    `json:"keyword"`
	Category    string    `json:"category"`
	Mentions    int32     `json:"mentions"`
	EmotionTone string    `json:"emotion_tone"`
	MentionedAt time.Time `json:"mentioned_at"`
}

// 시간 감쇠 갱신: score = score * 0.9 + 이번 세션 언급 수.
func (q *Queries) BumpKeyword(ctx context.Context, arg BumpKeywordParams) (KeywordTag, error) {
	row := q.db.QueryRow(ctx, bumpKeyword,
		arg.ElderID,
		arg.Keyword,
		arg.Category,
		arg.Mentions,
		arg.EmotionTone,
		arg.MentionedAt,
	)
	var i KeywordTag
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.Keyword,
		&i.Category,
		&i.Score,
		&i.EmotionTone,
		&i.LastMentionedAt,
		&i.MentionCountTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopKeywords = `-- name: ListTopKeywords :many
SELECT id, elder_id, keyword, category, score, emotion_tone, last_mentioned_at, mention_count_total, created_at, updated_at FROM keyword_tag
WHERE elder_id = $1
ORDER BY score DESC
LIMIT $2
`

type ListTopKeywordsParams struct {
	ElderID  uuid.UUID `json:"elder_id"`
	MaxCount int32     `json:"max_count"`
}

func (q *Queries) ListTopKeywords(ctx context.Context, arg ListTopKeywordsParams) ([]KeywordTag, error) {
	rows, err := q.db.Query(ctx, listTopKeywords, arg.ElderID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordTag{}
	for rows.Next() {
		var i KeywordTag
		if err := rows.Scan(
			&i.ID,
			&i.ElderID,
			&i.Keyword,
			&i.Category,
			&i.Score,
			&i.EmotionTone,
			&i.LastMentionedAt,
			&i.MentionCountTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
