// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCaregiverLocation = `-- name: CreateCaregiverLocation :exec
INSERT INTO caregiver_location (caregiver_id, visit_id, latitude, longitude, accuracy_m, eta_minutes, recorded_at)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateCaregiverLocationParams struct {
	CaregiverID uuid.UUID  `json:"caregiver_id"`
	VisitID     *uuid.UUID `json:"visit_id"`
	Latitude    float64    `json:"latitude"`
	Longitude   float64    `json:"longitude"`
	AccuracyM   *float64   `json:"accuracy_m"`
	EtaMinutes  *int32     `json:"eta_minutes"`
	RecordedAt  time.Time  `json:"recorded_at"`
}

func (q *Queries) CreateCaregiverLocation(ctx context.Context, arg CreateCaregiverLocationParams) error {
	_, err := q.db.Exec(ctx, createCaregiverLocation,
		arg.CaregiverID,
		arg.VisitID,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyM,
		arg.EtaMinutes,
		arg.RecordedAt,
	)
	return err
}

const deleteCaregiverLocationsBefore = `-- name: DeleteCaregiverLocationsBefore :execrows
DELETE FROM caregiver_location WHERE received_at < $1
`

func (q *Queries) DeleteCaregiverLocationsBefore(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCaregiverLocationsBefore, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
