// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BriefingReport struct {
	ID                uuid.UUID  `json:"id"`
	SessionID         uuid.UUID  `json:"session_id"`
	SummaryText       string     `json:"summary_text"`
	TopKeywords       []byte     `json:"top_keywords"`
	EmotionFlag       *string    `json:"emotion_flag"`
	Model             *string    `json:"model"`
	GeneratedAt       time.Time  `json:"generated_at"`
	ReadByCaregiverAt *time.Time `json:"read_by_caregiver_at"`
}

type Caregiver struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CenterID  uuid.UUID `json:"center_id"`
	CreatedAt time.Time `json:"created_at"`
}

type CaregiverLocation struct {
	ID          int64      `json:"id"`
	CaregiverID uuid.UUID  `json:"caregiver_id"`
	VisitID     *uuid.UUID `json:"visit_id"`
	Latitude    float64    `json:"latitude"`
	Longitude   float64    `json:"longitude"`
	AccuracyM   *float64   `json:"accuracy_m"`
	EtaMinutes  *int32     `json:"eta_minutes"`
	RecordedAt  time.Time  `json:"recorded_at"`
	ReceivedAt  time.Time  `json:"received_at"`
}

type CompanionSchedule struct {
	ElderID         uuid.UUID     `json:"elder_id"`
	Enabled         bool          `json:"enabled"`
	CheckInTimes    []pgtype.Time `json:"check_in_times"`
	BedtimeStart    pgtype.Time   `json:"bedtime_start"`
	BedtimeEnd      pgtype.Time   `json:"bedtime_end"`
	TimeZone        string        `json:"time_zone"`
	DailyTokenLimit *int32        `json:"daily_token_limit"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type ConversationSession struct {
	ID                uuid.UUID  `json:"id"`
	VisitID           *uuid.UUID `json:"visit_id"`
	ElderID           uuid.UUID  `json:"elder_id"`
	Mode              string     `json:"mode"`
	StartedBy         string     `json:"started_by"`
	StartedAt         time.Time  `json:"started_at"`
	EndedAt           *time.Time `json:"ended_at"`
	TriggerEtaMinutes *int32     `json:"trigger_eta_minutes"`
	OverallEmotionTag *string    `json:"overall_emotion_tag"`
	EndedReason       *string    `json:"ended_reason"`
	PromptVersion     *string    `json:"prompt_version"`
}

type DailyDigest struct {
	ID              uuid.UUID   `json:"id"`
	ElderID         uuid.UUID   `json:"elder_id"`
	DigestDate      pgtype.Date `json:"digest_date"`
	SummaryText     string      `json:"summary_text"`
	EmotionFlag     *string     `json:"emotion_flag"`
	SessionCount    int32       `json:"session_count"`
	EscalationCount int32       `json:"escalation_count"`
	TotalTokens     int32       `json:"total_tokens"`
	Model           *string     `json:"model"`
	GeneratedAt     time.Time   `json:"generated_at"`
	SentAt          *time.Time  `json:"sent_at"`
}

type DaycareCenter struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   *string   `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type Device struct {
	ID          uuid.UUID  `json:"id"`
	Kind        string     `json:"kind"`
	ElderID     *uuid.UUID `json:"elder_id"`
	CaregiverID *uuid.UUID `json:"caregiver_id"`
	GuardianID  *uuid.UUID `json:"guardian_id"`
	Label       *string    `json:"label"`
	TokenHash   []byte     `json:"token_hash"`
	FcmToken    *string    `json:"fcm_token"`
	LastSeenAt  *time.Time `json:"last_seen_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Elder struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	BirthDate         pgtype.Date `json:"birth_date"`
	DementiaStage     string      `json:"dementia_stage"`
	PreferredTtsVoice *string     `json:"preferred_tts_voice"`
	GuardianID        uuid.UUID   `json:"guardian_id"`
	CenterID          uuid.UUID   `json:"center_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type EscalationEvent struct {
	ID                        uuid.UUID  `json:"id"`
	SessionID                 uuid.UUID  `json:"session_id"`
	UtteranceID               *uuid.UUID `json:"utterance_id"`
	TriggerType               string     `json:"trigger_type"`
	Source                    string     `json:"source"`
	RuleID                    *string    `json:"rule_id"`
	Reason                    *string    `json:"reason"`
	NotifiedTargets           []byte     `json:"notified_targets"`
	CreatedAt                 time.Time  `json:"created_at"`
	AcknowledgedAt            *time.Time `json:"acknowledged_at"`
	AcknowledgedByCaregiverID *uuid.UUID `json:"acknowledged_by_caregiver_id"`
	ResolvedAt                *time.Time `json:"resolved_at"`
}

type Guardian struct {
	ID                     uuid.UUID `json:"id"`
	Name                   string    `json:"name"`
	Phone                  string    `json:"phone"`
	NotificationPreference []byte    `json:"notification_preference"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type KeywordTag struct {
	ID                uuid.UUID `json:"id"`
	ElderID           uuid.UUID `json:"elder_id"`
	Keyword           string    `json:"keyword"`
	Category          string    `json:"category"`
	Score             float64   `json:"score"`
	EmotionTone       string    `json:"emotion_tone"`
	LastMentionedAt   time.Time `json:"last_mentioned_at"`
	MentionCountTotal int32     `json:"mention_count_total"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type OpenerClip struct {
	ID         uuid.UUID `json:"id"`
	Category   string    `json:"category"`
	Text       string    `json:"text"`
	Voice      string    `json:"voice"`
	AudioRef   string    `json:"audio_ref"`
	DurationMs int32     `json:"duration_ms"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
}

type Utterance struct {
	ID           uuid.UUID  `json:"id"`
	SessionID    uuid.UUID  `json:"session_id"`
	Seq          int32      `json:"seq"`
	ChunkIndex   int32      `json:"chunk_index"`
	Speaker      string     `json:"speaker"`
	Text         string     `json:"text"`
	AudioRef     *string    `json:"audio_ref"`
	EmotionScore *float64   `json:"emotion_score"`
	FlaggedRisk  bool       `json:"flagged_risk"`
	OpenerClipID *uuid.UUID `json:"opener_clip_id"`
	Model        *string    `json:"model"`
	LatencyMs    *int32     `json:"latency_ms"`
	InputTokens  *int32     `json:"input_tokens"`
	OutputTokens *int32     `json:"output_tokens"`
	CreatedAt    time.Time  `json:"created_at"`
}

type Visit struct {
	ID                uuid.UUID  `json:"id"`
	ElderID           uuid.UUID  `json:"elder_id"`
	CaregiverID       uuid.UUID  `json:"caregiver_id"`
	ScheduledTime     time.Time  `json:"scheduled_time"`
	EtaCurrent        *time.Time `json:"eta_current"`
	Status            string     `json:"status"`
	ActualArrivalTime *time.Time `json:"actual_arrival_time"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}
