// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: openers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOpenerClip = `-- name: GetOpenerClip :one
SELECT id, category, text, voice, audio_ref, duration_ms, active, created_at FROM opener_clip WHERE id = $1
`

func (q *Queries) GetOpenerClip(ctx context.Context, id uuid.UUID) (OpenerClip, error) {
	row := q.db.QueryRow(ctx, getOpenerClip, id)
	var i OpenerClip
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Text,
		&i.Voice,
		&i.AudioRef,
		&i.DurationMs,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOpenerClips = `-- name: ListActiveOpenerClips :many
SELECT id, category, text, voice, audio_ref, duration_ms, active, created_at FROM opener_clip
WHERE voice = $1
  AND active
ORDER BY category, id
`

// 태블릿이 내려받을 0번 문장 목록. 어르신의 preferred_tts_voice로 거릅니다.
func (q *Queries) ListActiveOpenerClips(ctx context.Context, voice string) ([]OpenerClip, error) {
	rows, err := q.db.Query(ctx, listActiveOpenerClips, voice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenerClip{}
	for rows.Next() {
		var i OpenerClip
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Text,
			&i.Voice,
			&i.AudioRef,
			&i.DurationMs,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
