// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCompanionSession = `-- name: CreateCompanionSession :one
INSERT INTO conversation_session (elder_id, mode, started_by, prompt_version)
VALUES ($1, 'COMPANION', $2, $3)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type CreateCompanionSessionParams struct {
	ElderID       uuid.UUID `json:"elder_id"`
	StartedBy     string    `json:"started_by"`
	PromptVersion *string   `json:"prompt_version"`
}

// 어르신당 진행 중 세션은 하나뿐이라(부분 유니크 인덱스) 이미 대화 중이면 유니크 위반으로 실패합니다.
func (q *Queries) CreateCompanionSession(ctx context.Context, arg CreateCompanionSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createCompanionSession, arg.ElderID, arg.StartedBy, arg.PromptVersion)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const createPickupSession = `-- name: CreatePickupSession :one
INSERT INTO conversation_session (visit_id, elder_id, mode, started_by, trigger_eta_minutes, prompt_version)
VALUES ($1, $2, 'PICKUP_BRIDGE', 'SYSTEM', $3, $4)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type CreatePickupSessionParams struct {
	VisitID           *uuid.UUID `json:"visit_id"`
	ElderID           uuid.UUID  `json:"elder_id"`
	TriggerEtaMinutes *int32     `json:"trigger_eta_minutes"`
	PromptVersion     *string    `json:"prompt_version"`
}

func (q *Queries) CreatePickupSession(ctx context.Context, arg CreatePickupSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createPickupSession,
		arg.VisitID,
		arg.ElderID,
		arg.TriggerEtaMinutes,
		arg.PromptVersion,
	)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE conversation_session
SET ended_at = now(),
    ended_reason = $1
WHERE id = $2
  AND ended_at IS NULL
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type EndSessionParams struct {
	EndedReason *string   `json:"ended_reason"`
	ID          uuid.UUID `json:"id"`
}

// 이미 끝난 세션이면 행이 없습니다.
func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, endSession, arg.EndedReason, arg.ID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getOpenSessionForElder = `-- name: GetOpenSessionForElder :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE elder_id = $1 AND ended_at IS NULL
`

func (q *Queries) GetOpenSessionForElder(ctx context.Context, elderID uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getOpenSessionForElder, elderID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getSessionByVisit = `-- name: GetSessionByVisit :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE visit_id = $1
`

func (q *Queries) GetSessionByVisit(ctx context.Context, visitID *uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSessionByVisit, visitID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}
