// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCompanionSession = `-- name: CreateCompanionSession :one
INSERT INTO conversation_session (elder_id, mode, started_by, prompt_version)
VALUES ($1, 'COMPANION', $2, $3)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through
`

type CreateCompanionSessionParams struct {
	ElderID       uuid.UUID `json:"elder_id"`
	StartedBy     string    `json:"started_by"`
	PromptVersion *string   `json:"prompt_version"`
}

// 어르신당 진행 중 세션은 하나뿐이라(부분 유니크 인덱스) 이미 대화 중이면 유니크 위반으로 실패합니다.
func (q *Queries) CreateCompanionSession(ctx context.Context, arg CreateCompanionSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createCompanionSession, arg.ElderID, arg.StartedBy, arg.PromptVersion)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const createPickupSession = `-- name: CreatePickupSession :one
INSERT INTO conversation_session (visit_id, elder_id, mode, started_by, trigger_eta_minutes, prompt_version)
VALUES ($1, $2, 'PICKUP_BRIDGE', 'SYSTEM', $3, $4)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through
`

type CreatePickupSessionParams struct {
	VisitID           *uuid.UUID `json:"visit_id"`
	ElderID           uuid.UUID  `json:"elder_id"`
	TriggerEtaMinutes *int32     `json:"trigger_eta_minutes"`
	PromptVersion     *string    `json:"prompt_version"`
}

func (q *Queries) CreatePickupSession(ctx context.Context, arg CreatePickupSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createPickupSession,
		arg.VisitID,
		arg.ElderID,
		arg.TriggerEtaMinutes,
		arg.PromptVersion,
	)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE conversation_session
SET ended_at = now(),
    ended_reason = $1
WHERE id = $2
  AND ended_at IS NULL
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through
`

type EndSessionParams struct {
	EndedReason *string   `json:"ended_reason"`
	ID          uuid.UUID `json:"id"`
}

// 이미 끝난 세션이면 행이 없습니다.
func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, endSession, arg.EndedReason, arg.ID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const getOpenSessionForElder = `-- name: GetOpenSessionForElder :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through FROM conversation_session WHERE elder_id = $1 AND ended_at IS NULL
`

func (q *Queries) GetOpenSessionForElder(ctx context.Context, elderID uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getOpenSessionForElder, elderID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through FROM conversation_session WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const getSessionByVisit = `-- name: GetSessionByVisit :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through FROM conversation_session WHERE visit_id = $1
`

func (q *Queries) GetSessionByVisit(ctx context.Context, visitID *uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSessionByVisit, visitID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const getSessionOwner = `-- name: GetSessionOwner :one
SELECT
    conversation_session.id, conversation_session.visit_id, conversation_session.elder_id, conversation_session.mode, conversation_session.started_by, conversation_session.started_at, conversation_session.ended_at, conversation_session.trigger_eta_minutes, conversation_session.overall_emotion_tag, conversation_session.ended_reason, conversation_session.prompt_version, conversation_session.history_summary, conversation_session.history_summary_through,
    elder.name AS elder_name,
    visit.caregiver_id AS caregiver_id
FROM conversation_session
JOIN elder ON elder.id = conversation_session.elder_id
LEFT JOIN visit ON visit.id = conversation_session.visit_id
WHERE conversation_session.id = $1
`

type GetSessionOwnerRow struct {
	ConversationSession ConversationSession `json:"conversation_session"`
	ElderName           string              `json:"elder_name"`
	CaregiverID         *uuid.UUID          `json:"caregiver_id"`
}

// 세션의 어르신과, 픽업 세션이면 그 방문의 조무사.
func (q *Queries) GetSessionOwner(ctx context.Context, id uuid.UUID) (GetSessionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getSessionOwner, id)
	var i GetSessionOwnerRow
	err := row.Scan(
		&i.ConversationSession.ID,
		&i.ConversationSession.VisitID,
		&i.ConversationSession.ElderID,
		&i.ConversationSession.Mode,
		&i.ConversationSession.StartedBy,
		&i.ConversationSession.StartedAt,
		&i.ConversationSession.EndedAt,
		&i.ConversationSession.TriggerEtaMinutes,
		&i.ConversationSession.OverallEmotionTag,
		&i.ConversationSession.EndedReason,
		&i.ConversationSession.PromptVersion,
		&i.ConversationSession.HistorySummary,
		&i.ConversationSession.HistorySummaryThrough,
		&i.ElderName,
		&i.CaregiverID,
	)
	return i, err
}

const hasScheduledSessionSince = `-- name: HasScheduledSessionSince :one
SELECT EXISTS (
    SELECT 1 FROM conversation_session
    WHERE elder_id = $1
      AND started_by = 'SCHEDULE'
      AND started_at >= $2
) AS started
`

type HasScheduledSessionSinceParams struct {
	ElderID uuid.UUID `json:"elder_id"`
	Since   time.Time `json:"since"`
}

// 그 안부 시각에 이미 안부 대화를 시작했는지.
func (q *Queries) HasScheduledSessionSince(ctx context.Context, arg HasScheduledSessionSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasScheduledSessionSince, arg.ElderID, arg.Since)
	var started bool
	err := row.Scan(&started)
	return started, err
}

const listElderSessionsBetween = `-- name: ListElderSessionsBetween :many
SELECT
    conversation_session.id, conversation_session.visit_id, conversation_session.elder_id, conversation_session.mode, conversation_session.started_by, conversation_session.started_at, conversation_session.ended_at, conversation_session.trigger_eta_minutes, conversation_session.overall_emotion_tag, conversation_session.ended_reason, conversation_session.prompt_version, conversation_session.history_summary, conversation_session.history_summary_through,
    briefing_report.summary_text,
    briefing_report.emotion_flag
FROM conversation_session
LEFT JOIN briefing_report ON briefing_report.session_id = conversation_session.id
WHERE conversation_session.elder_id = $1
  AND conversation_session.mode = 'COMPANION'
  AND conversation_session.started_at >= $2
  AND conversation_session.started_at < $3
ORDER BY conversation_session.started_at
`

type ListElderSessionsBetweenParams struct {
	ElderID  uuid.UUID `json:"elder_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type ListElderSessionsBetweenRow struct {
	ConversationSession ConversationSession `json:"conversation_session"`
	SummaryText         *string             `json:"summary_text"`
	EmotionFlag         *string             `json:"emotion_flag"`
}

// 하루 요약용: 그날 끝난 말동무 세션과 브리핑(없으면 NULL).
func (q *Queries) ListElderSessionsBetween(ctx context.Context, arg ListElderSessionsBetweenParams) ([]ListElderSessionsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listElderSessionsBetween, arg.ElderID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListElderSessionsBetweenRow{}
	for rows.Next() {
		var i ListElderSessionsBetweenRow
		if err := rows.Scan(
			&i.ConversationSession.ID,
			&i.ConversationSession.VisitID,
			&i.ConversationSession.ElderID,
			&i.ConversationSession.Mode,
			&i.ConversationSession.StartedBy,
			&i.ConversationSession.StartedAt,
			&i.ConversationSession.EndedAt,
			&i.ConversationSession.TriggerEtaMinutes,
			&i.ConversationSession.OverallEmotionTag,
			&i.ConversationSession.EndedReason,
			&i.ConversationSession.PromptVersion,
			&i.ConversationSession.HistorySummary,
			&i.ConversationSession.HistorySummaryThrough,
			&i.SummaryText,
			&i.EmotionFlag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEldersWithCompanionBetween = `-- name: ListEldersWithCompanionBetween :many
SELECT DISTINCT elder_id
FROM conversation_session
WHERE mode = 'COMPANION'
  AND started_at >= $1
  AND started_at < $2
`

type ListEldersWithCompanionBetweenParams struct {
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

// 하루 요약을 만들 어르신: 그날 말동무 대화가 있었던 어르신.
func (q *Queries) ListEldersWithCompanionBetween(ctx context.Context, arg ListEldersWithCompanionBetweenParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEldersWithCompanionBetween, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var elder_id uuid.UUID
		if err := rows.Scan(&elder_id); err != nil {
			return nil, err
		}
		items = append(items, elder_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCompanionSessions = `-- name: ListOpenCompanionSessions :many
SELECT
    conversation_session.id, conversation_session.visit_id, conversation_session.elder_id, conversation_session.mode, conversation_session.started_by, conversation_session.started_at, conversation_session.ended_at, conversation_session.trigger_eta_minutes, conversation_session.overall_emotion_tag, conversation_session.ended_reason, conversation_session.prompt_version, conversation_session.history_summary, conversation_session.history_summary_through,
    COALESCE(
        (SELECT max(u.created_at) FROM utterance u WHERE u.session_id = conversation_session.id),
        conversation_session.started_at
    )::timestamptz AS last_activity_at
FROM conversation_session
WHERE mode = 'COMPANION' AND ended_at IS NULL
`

type ListOpenCompanionSessionsRow struct {
	ConversationSession ConversationSession `json:"conversation_session"`
	LastActivityAt      time.Time           `json:"last_activity_at"`
}

// 무응답·취침 시간 종료를 확인할 진행 중 말동무 세션과 마지막 발화 시각.
func (q *Queries) ListOpenCompanionSessions(ctx context.Context) ([]ListOpenCompanionSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenCompanionSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCompanionSessionsRow{}
	for rows.Next() {
		var i ListOpenCompanionSessionsRow
		if err := rows.Scan(
			&i.ConversationSession.ID,
			&i.ConversationSession.VisitID,
			&i.ConversationSession.ElderID,
			&i.ConversationSession.Mode,
			&i.ConversationSession.StartedBy,
			&i.ConversationSession.StartedAt,
			&i.ConversationSession.EndedAt,
			&i.ConversationSession.TriggerEtaMinutes,
			&i.ConversationSession.OverallEmotionTag,
			&i.ConversationSession.EndedReason,
			&i.ConversationSession.PromptVersion,
			&i.ConversationSession.HistorySummary,
			&i.ConversationSession.HistorySummaryThrough,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preemptCompanionSession = `-- name: PreemptCompanionSession :one
UPDATE conversation_session
SET ended_at = now(),
    ended_reason = 'PREEMPTED'
WHERE elder_id = $1
  AND mode = 'COMPANION'
  AND ended_at IS NULL
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version, history_summary, history_summary_through
`

// 픽업 대기 세션을 시작하기 전에 진행 중인 말동무 세션을 끝냅니다. 없으면 행이 없습니다.
func (q *Queries) PreemptCompanionSession(ctx context.Context, elderID uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, preemptCompanionSession, elderID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
		&i.HistorySummary,
		&i.HistorySummaryThrough,
	)
	return i, err
}

const setHistorySummary = `-- name: SetHistorySummary :exec
UPDATE conversation_session
SET history_summary = $1,
    history_summary_through = $2
WHERE id = $3
  AND (history_summary_through IS NULL OR history_summary_through < $2)
`

type SetHistorySummaryParams struct {
	Summary *string   `json:"summary"`
	Through *int32    `json:"through"`
	ID      uuid.UUID `json:"id"`
}

// 더 앞선 요약으로 덮어쓰지 않습니다(작업이 늦게 끝나도 안전).
func (q *Queries) SetHistorySummary(ctx context.Context, arg SetHistorySummaryParams) error {
	_, err := q.db.Exec(ctx, setHistorySummary, arg.Summary, arg.Through, arg.ID)
	return err
}

const setSessionEmotionTag = `-- name: SetSessionEmotionTag :exec
UPDATE conversation_session SET overall_emotion_tag = $1 WHERE id = $2
`

type SetSessionEmotionTagParams struct {
	Tag *string   `json:"tag"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) SetSessionEmotionTag(ctx context.Context, arg SetSessionEmotionTagParams) error {
	_, err := q.db.Exec(ctx, setSessionEmotionTag, arg.Tag, arg.ID)
	return err
}
