// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCompanionSession = `-- name: CreateCompanionSession :one
INSERT INTO conversation_session (elder_id, mode, started_by, prompt_version)
VALUES ($1, 'COMPANION', $2, $3)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type CreateCompanionSessionParams struct {
	ElderID       uuid.UUID `json:"elder_id"`
	StartedBy     string    `json:"started_by"`
	PromptVersion *string   `json:"prompt_version"`
}

// 어르신당 진행 중 세션은 하나뿐이라(부분 유니크 인덱스) 이미 대화 중이면 유니크 위반으로 실패합니다.
func (q *Queries) CreateCompanionSession(ctx context.Context, arg CreateCompanionSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createCompanionSession, arg.ElderID, arg.StartedBy, arg.PromptVersion)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const createPickupSession = `-- name: CreatePickupSession :one
INSERT INTO conversation_session (visit_id, elder_id, mode, started_by, trigger_eta_minutes, prompt_version)
VALUES ($1, $2, 'PICKUP_BRIDGE', 'SYSTEM', $3, $4)
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type CreatePickupSessionParams struct {
	VisitID           *uuid.UUID `json:"visit_id"`
	ElderID           uuid.UUID  `json:"elder_id"`
	TriggerEtaMinutes *int32     `json:"trigger_eta_minutes"`
	PromptVersion     *string    `json:"prompt_version"`
}

func (q *Queries) CreatePickupSession(ctx context.Context, arg CreatePickupSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createPickupSession,
		arg.VisitID,
		arg.ElderID,
		arg.TriggerEtaMinutes,
		arg.PromptVersion,
	)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE conversation_session
SET ended_at = now(),
    ended_reason = $1
WHERE id = $2
  AND ended_at IS NULL
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

type EndSessionParams struct {
	EndedReason *string   `json:"ended_reason"`
	ID          uuid.UUID `json:"id"`
}

// 이미 끝난 세션이면 행이 없습니다.
func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, endSession, arg.EndedReason, arg.ID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getOpenSessionForElder = `-- name: GetOpenSessionForElder :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE elder_id = $1 AND ended_at IS NULL
`

func (q *Queries) GetOpenSessionForElder(ctx context.Context, elderID uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getOpenSessionForElder, elderID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getSessionByVisit = `-- name: GetSessionByVisit :one
SELECT id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version FROM conversation_session WHERE visit_id = $1
`

func (q *Queries) GetSessionByVisit(ctx context.Context, visitID *uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSessionByVisit, visitID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const getSessionOwner = `-- name: GetSessionOwner :one
SELECT
    conversation_session.id, conversation_session.visit_id, conversation_session.elder_id, conversation_session.mode, conversation_session.started_by, conversation_session.started_at, conversation_session.ended_at, conversation_session.trigger_eta_minutes, conversation_session.overall_emotion_tag, conversation_session.ended_reason, conversation_session.prompt_version,
    elder.name AS elder_name,
    visit.caregiver_id AS caregiver_id
FROM conversation_session
JOIN elder ON elder.id = conversation_session.elder_id
LEFT JOIN visit ON visit.id = conversation_session.visit_id
WHERE conversation_session.id = $1
`

type GetSessionOwnerRow struct {
	ConversationSession ConversationSession `json:"conversation_session"`
	ElderName           string              `json:"elder_name"`
	CaregiverID         *uuid.UUID          `json:"caregiver_id"`
}

// 세션의 어르신과, 픽업 세션이면 그 방문의 조무사.
func (q *Queries) GetSessionOwner(ctx context.Context, id uuid.UUID) (GetSessionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getSessionOwner, id)
	var i GetSessionOwnerRow
	err := row.Scan(
		&i.ConversationSession.ID,
		&i.ConversationSession.VisitID,
		&i.ConversationSession.ElderID,
		&i.ConversationSession.Mode,
		&i.ConversationSession.StartedBy,
		&i.ConversationSession.StartedAt,
		&i.ConversationSession.EndedAt,
		&i.ConversationSession.TriggerEtaMinutes,
		&i.ConversationSession.OverallEmotionTag,
		&i.ConversationSession.EndedReason,
		&i.ConversationSession.PromptVersion,
		&i.ElderName,
		&i.CaregiverID,
	)
	return i, err
}

const preemptCompanionSession = `-- name: PreemptCompanionSession :one
UPDATE conversation_session
SET ended_at = now(),
    ended_reason = 'PREEMPTED'
WHERE elder_id = $1
  AND mode = 'COMPANION'
  AND ended_at IS NULL
RETURNING id, visit_id, elder_id, mode, started_by, started_at, ended_at, trigger_eta_minutes, overall_emotion_tag, ended_reason, prompt_version
`

// 픽업 대기 세션을 시작하기 전에 진행 중인 말동무 세션을 끝냅니다. 없으면 행이 없습니다.
func (q *Queries) PreemptCompanionSession(ctx context.Context, elderID uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, preemptCompanionSession, elderID)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.ElderID,
		&i.Mode,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.TriggerEtaMinutes,
		&i.OverallEmotionTag,
		&i.EndedReason,
		&i.PromptVersion,
	)
	return i, err
}

const setSessionEmotionTag = `-- name: SetSessionEmotionTag :exec
UPDATE conversation_session SET overall_emotion_tag = $1 WHERE id = $2
`

type SetSessionEmotionTagParams struct {
	Tag *string   `json:"tag"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) SetSessionEmotionTag(ctx context.Context, arg SetSessionEmotionTagParams) error {
	_, err := q.db.Exec(ctx, setSessionEmotionTag, arg.Tag, arg.ID)
	return err
}
