// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: utterances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUtterance = `-- name: CreateUtterance :one
INSERT INTO utterance (
    session_id, seq, chunk_index, speaker, text, audio_ref, emotion_score, flagged_risk,
    opener_clip_id, model, latency_ms, input_tokens, output_tokens
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
RETURNING id, session_id, seq, chunk_index, speaker, text, audio_ref, emotion_score, flagged_risk, opener_clip_id, model, latency_ms, input_tokens, output_tokens, created_at
`

type CreateUtteranceParams struct {
	SessionID    uuid.UUID  `json:"session_id"`
	Seq          int32      `json:"seq"`
	ChunkIndex   int32      `json:"chunk_index"`
	Speaker      string     `json:"speaker"`
	Text         string     `json:"text"`
	AudioRef     *string    `json:"audio_ref"`
	EmotionScore *float64   `json:"emotion_score"`
	FlaggedRisk  bool       `json:"flagged_risk"`
	OpenerClipID *uuid.UUID `json:"opener_clip_id"`
	Model        *string    `json:"model"`
	LatencyMs    *int32     `json:"latency_ms"`
	InputTokens  *int32     `json:"input_tokens"`
	OutputTokens *int32     `json:"output_tokens"`
}

func (q *Queries) CreateUtterance(ctx context.Context, arg CreateUtteranceParams) (Utterance, error) {
	row := q.db.QueryRow(ctx, createUtterance,
		arg.SessionID,
		arg.Seq,
		arg.ChunkIndex,
		arg.Speaker,
		arg.Text,
		arg.AudioRef,
		arg.EmotionScore,
		arg.FlaggedRisk,
		arg.OpenerClipID,
		arg.Model,
		arg.LatencyMs,
		arg.InputTokens,
		arg.OutputTokens,
	)
	var i Utterance
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.ChunkIndex,
		&i.Speaker,
		&i.Text,
		&i.AudioRef,
		&i.EmotionScore,
		&i.FlaggedRisk,
		&i.OpenerClipID,
		&i.Model,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionUtterances = `-- name: ListSessionUtterances :many
SELECT id, session_id, seq, chunk_index, speaker, text, audio_ref, emotion_score, flagged_risk, opener_clip_id, model, latency_ms, input_tokens, output_tokens, created_at FROM utterance WHERE session_id = $1 ORDER BY seq, chunk_index
`

func (q *Queries) ListSessionUtterances(ctx context.Context, sessionID uuid.UUID) ([]Utterance, error) {
	rows, err := q.db.Query(ctx, listSessionUtterances, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Utterance{}
	for rows.Next() {
		var i Utterance
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.ChunkIndex,
			&i.Speaker,
			&i.Text,
			&i.AudioRef,
			&i.EmotionScore,
			&i.FlaggedRisk,
			&i.OpenerClipID,
			&i.Model,
			&i.LatencyMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextUtteranceSeq = `-- name: NextUtteranceSeq :one
SELECT COALESCE(MAX(seq) + 1, 0)::integer AS next_seq FROM utterance WHERE session_id = $1
`

func (q *Queries) NextUtteranceSeq(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextUtteranceSeq, sessionID)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const setUtteranceUsage = `-- name: SetUtteranceUsage :exec
UPDATE utterance
SET model = $1,
    input_tokens = $2,
    output_tokens = $3
WHERE id = $4
`

type SetUtteranceUsageParams struct {
	Model        *string   `json:"model"`
	InputTokens  *int32    `json:"input_tokens"`
	OutputTokens *int32    `json:"output_tokens"`
	ID           uuid.UUID `json:"id"`
}

// 한 턴의 Claude 모델·토큰 사용량은 스트리밍이 끝난 뒤에 알 수 있어 그 턴의 마지막 문장에 기록합니다.
func (q *Queries) SetUtteranceUsage(ctx context.Context, arg SetUtteranceUsageParams) error {
	_, err := q.db.Exec(ctx, setUtteranceUsage,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ID,
	)
	return err
}

const sumElderTokensSince = `-- name: SumElderTokensSince :one
SELECT COALESCE(SUM(COALESCE(u.input_tokens, 0) + COALESCE(u.output_tokens, 0)), 0)::bigint AS total_tokens
FROM utterance u
JOIN conversation_session s ON s.id = u.session_id
WHERE s.elder_id = $1
  AND u.created_at >= $2
`

type SumElderTokensSinceParams struct {
	ElderID uuid.UUID `json:"elder_id"`
	Since   time.Time `json:"since"`
}

// 말동무 하루 토큰 한도 확인용.
func (q *Queries) SumElderTokensSince(ctx context.Context, arg SumElderTokensSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumElderTokensSince, arg.ElderID, arg.Since)
	var total_tokens int64
	err := row.Scan(&total_tokens)
	return total_tokens, err
}
