// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visits.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimVisitSession = `-- name: ClaimVisitSession :one
UPDATE visit
SET status = 'SESSION_ACTIVE'
WHERE id = $1
  AND status IN ('SCHEDULED', 'EN_ROUTE')
RETURNING id, elder_id, caregiver_id, scheduled_time, eta_current, status, actual_arrival_time, created_at, updated_at
`

// 세션 시작 권한을 한 문장으로 차지합니다. 위치가 동시에 두 번 와도 한 요청만 행을 돌려받고,
// 나머지는 pgx.ErrNoRows를 받습니다. 같은 트랜잭션에서 CreatePickupSession을 이어서 호출합니다.
func (q *Queries) ClaimVisitSession(ctx context.Context, id uuid.UUID) (Visit, error) {
	row := q.db.QueryRow(ctx, claimVisitSession, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.CaregiverID,
		&i.ScheduledTime,
		&i.EtaCurrent,
		&i.Status,
		&i.ActualArrivalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeVisit = `-- name: CompleteVisit :one
UPDATE visit
SET status = 'COMPLETED',
    actual_arrival_time = $1
WHERE id = $2
  AND status IN ('SCHEDULED', 'EN_ROUTE', 'SESSION_ACTIVE')
RETURNING id, elder_id, caregiver_id, scheduled_time, eta_current, status, actual_arrival_time, created_at, updated_at
`

type CompleteVisitParams struct {
	ArrivedAt *time.Time `json:"arrived_at"`
	ID        uuid.UUID  `json:"id"`
}

// 조무사 도착. 이미 완료·취소된 방문이면 행이 없습니다.
func (q *Queries) CompleteVisit(ctx context.Context, arg CompleteVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, completeVisit, arg.ArrivedAt, arg.ID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.CaregiverID,
		&i.ScheduledTime,
		&i.EtaCurrent,
		&i.Status,
		&i.ActualArrivalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisit = `-- name: GetVisit :one
SELECT id, elder_id, caregiver_id, scheduled_time, eta_current, status, actual_arrival_time, created_at, updated_at FROM visit WHERE id = $1
`

func (q *Queries) GetVisit(ctx context.Context, id uuid.UUID) (Visit, error) {
	row := q.db.QueryRow(ctx, getVisit, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.CaregiverID,
		&i.ScheduledTime,
		&i.EtaCurrent,
		&i.Status,
		&i.ActualArrivalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisitDetail = `-- name: GetVisitDetail :one
SELECT
    visit.id, visit.elder_id, visit.caregiver_id, visit.scheduled_time, visit.eta_current, visit.status, visit.actual_arrival_time, visit.created_at, visit.updated_at,
    elder.name AS elder_name,
    elder.home_address,
    elder.home_latitude,
    elder.home_longitude,
    conversation_session.id AS session_id
FROM visit
JOIN elder ON elder.id = visit.elder_id
LEFT JOIN conversation_session ON conversation_session.visit_id = visit.id
WHERE visit.id = $1
`

type GetVisitDetailRow struct {
	Visit         Visit      `json:"visit"`
	ElderName     string     `json:"elder_name"`
	HomeAddress   *string    `json:"home_address"`
	HomeLatitude  *float64   `json:"home_latitude"`
	HomeLongitude *float64   `json:"home_longitude"`
	SessionID     *uuid.UUID `json:"session_id"`
}

// API 응답용: 어르신 이름·댁 위치와 픽업 대기 세션 ID를 함께 읽습니다.
func (q *Queries) GetVisitDetail(ctx context.Context, id uuid.UUID) (GetVisitDetailRow, error) {
	row := q.db.QueryRow(ctx, getVisitDetail, id)
	var i GetVisitDetailRow
	err := row.Scan(
		&i.Visit.ID,
		&i.Visit.ElderID,
		&i.Visit.CaregiverID,
		&i.Visit.ScheduledTime,
		&i.Visit.EtaCurrent,
		&i.Visit.Status,
		&i.Visit.ActualArrivalTime,
		&i.Visit.CreatedAt,
		&i.Visit.UpdatedAt,
		&i.ElderName,
		&i.HomeAddress,
		&i.HomeLatitude,
		&i.HomeLongitude,
		&i.SessionID,
	)
	return i, err
}

const listCaregiverVisitsBetween = `-- name: ListCaregiverVisitsBetween :many
SELECT
    visit.id, visit.elder_id, visit.caregiver_id, visit.scheduled_time, visit.eta_current, visit.status, visit.actual_arrival_time, visit.created_at, visit.updated_at,
    elder.name AS elder_name,
    elder.home_address,
    elder.home_latitude,
    elder.home_longitude,
    conversation_session.id AS session_id
FROM visit
JOIN elder ON elder.id = visit.elder_id
LEFT JOIN conversation_session ON conversation_session.visit_id = visit.id
WHERE visit.caregiver_id = $1
  AND visit.scheduled_time >= $2
  AND visit.scheduled_time < $3
ORDER BY visit.scheduled_time
`

type ListCaregiverVisitsBetweenParams struct {
	CaregiverID uuid.UUID `json:"caregiver_id"`
	FromTime    time.Time `json:"from_time"`
	ToTime      time.Time `json:"to_time"`
}

type ListCaregiverVisitsBetweenRow struct {
	Visit         Visit      `json:"visit"`
	ElderName     string     `json:"elder_name"`
	HomeAddress   *string    `json:"home_address"`
	HomeLatitude  *float64   `json:"home_latitude"`
	HomeLongitude *float64   `json:"home_longitude"`
	SessionID     *uuid.UUID `json:"session_id"`
}

// 조무사 앱의 오늘 방문 목록. [from, to) 구간은 호출하는 쪽이 한국 시각 하루로 계산합니다.
func (q *Queries) ListCaregiverVisitsBetween(ctx context.Context, arg ListCaregiverVisitsBetweenParams) ([]ListCaregiverVisitsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listCaregiverVisitsBetween, arg.CaregiverID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCaregiverVisitsBetweenRow{}
	for rows.Next() {
		var i ListCaregiverVisitsBetweenRow
		if err := rows.Scan(
			&i.Visit.ID,
			&i.Visit.ElderID,
			&i.Visit.CaregiverID,
			&i.Visit.ScheduledTime,
			&i.Visit.EtaCurrent,
			&i.Visit.Status,
			&i.Visit.ActualArrivalTime,
			&i.Visit.CreatedAt,
			&i.Visit.UpdatedAt,
			&i.ElderName,
			&i.HomeAddress,
			&i.HomeLatitude,
			&i.HomeLongitude,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVisitEta = `-- name: RecordVisitEta :one
UPDATE visit
SET eta_current = $1,
    status = CASE WHEN status = 'SCHEDULED' THEN 'EN_ROUTE' ELSE status END
WHERE id = $2
  AND status IN ('SCHEDULED', 'EN_ROUTE', 'SESSION_ACTIVE')
RETURNING id, elder_id, caregiver_id, scheduled_time, eta_current, status, actual_arrival_time, created_at, updated_at
`

type RecordVisitEtaParams struct {
	EtaCurrent *time.Time `json:"eta_current"`
	ID         uuid.UUID  `json:"id"`
}

// 위치를 받을 때마다 ETA를 갱신하고, 예정 상태면 이동중으로 바꿉니다.
// 끝난 방문(완료·취소)은 건드리지 않으므로 행이 없으면 없는 방문이거나 끝난 방문입니다.
func (q *Queries) RecordVisitEta(ctx context.Context, arg RecordVisitEtaParams) (Visit, error) {
	row := q.db.QueryRow(ctx, recordVisitEta, arg.EtaCurrent, arg.ID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.ElderID,
		&i.CaregiverID,
		&i.ScheduledTime,
		&i.EtaCurrent,
		&i.Status,
		&i.ActualArrivalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
